version: '3.7'

services:
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

  php:
    image: akeylimepie/php-fpm:7.2-latest-dev
    volumes:
      - .:/var/www
    depends_on:
      - memcached
